### ISSUE TITLE
sim900_read_buffer, Suli not quickly enough ?

### ISSUE THREAD

**Issue by ortegafernando** [Seeed-Studio/GPRS_Shield_Suli#11]
Is sim900_read_buffer funtion you have an strange comment:

_Anyway, Suli is not quickly enough to fetch data from buffer, so 
    we have to fetch our data like this._

It is inside an ´#if false  #else   #endif`.

But why you can use the first part if it is used in sim900_wait_for_resp function ???

**Comment by KillingJacky** [comment]
Hi op2op2op2, actually we're stopping updating suli becuase it's not a user-friendly framework. So we stopped to iterate the suli based libraries.

**Comment by KillingJacky** [comment]
@op2op2op2, the author of this library has quit seeed. if you have time, would you like to rewrite this library in non-suli style?

**Comment by op2op2op2** [comment]
What a pity, the idea was, AND is, great.

**Comment by op2op2op2** [comment]
How can I send to you a private message ?

**Comment by KillingJacky** [comment]
xuguang.shao@seeed.cc

-- 
Jacky.Shaoxg@foxmail.com
Sent with Airmail

On April 8, 2015 at 18:07:04, op2op2op2 (notifications@github.com) wrote:

How can I send to you a private message ?
