### ISSUE TITLE
Send SMS example not working

### ISSUE THREAD

**Issue by Mrfixit44** [Seeed-Studio/GPRS_Shield_Suli#12]
Hello,
I'm new to this, I have a v2 of the GPRS shield. The Shield works with the serial example on the Wiki page so the board works and so does the SIM card.
I installed the library. open up the Send SMS example, and change the number. This is where things get a little weird. 
I upload the sketch, with the modem off power up then turn on the modem and wait for the green light to blink once every 3 seconds. Then open the Arduino serial monitor and get the message

init error

If I power off the modem with the Arduino serial monitor still open it will say 

gprs init success
start to send message..

and nothing happens. 

suggestions? 
Thanks,
J

**Comment by kenken64** [comment]
Same here ...

**Comment by lanselambor** [comment]
Generally message sending should wait for network being registered.
