### ISSUE TITLE
wait_readable is not waiting - mistake in code

### ISSUE THREAD

**Issue by ranm** [Seeed-Studio/GPRS_Shield_Suli#14]
in "sim900_wait_readable"

instead of :
while((unsigned long) (millis() - timerStart) > wait_time \* 1000UL)

should be 

while((unsigned long) (millis() - timerStart) < wait_time \* 1000UL)

(the comparison is the wrong way so it never waits ....)

**Comment by lanselambor** [comment]
ranm,

Thank you, the issuse has been resolved...

**Comment by ranm** [comment]
Hey , 
Are you merging this to the non suli project as well ?
