### ISSUE TITLE
the library has some issues. please help me out there, thank you.

### ISSUE THREAD

**Issue by Jrius4** [Seeed-Studio/GPRS_Shield_Suli#15]
![err](https://user-images.githubusercontent.com/30425075/38780844-5f35885a-40e5-11e8-8956-5f3d554afe9f.png)

am facing these problem

**Comment by lanselambor** [comment]
@Jrius4 Please add this library to your Arduino environment, https://github.com/Seeed-Studio/Suli/blob/master/Suli_Arduino.
