### ISSUE TITLE
SMS works fine, but can't open TCP/IP connection

### ISSUE THREAD

**Issue by goodwordalchemy** [Seeed-Studio/GPRS_Shield_Suli#4]
I have a SIM from an att gophone hotspot.  It's data only.  I'm sure there is data available, but no voice and messaging.  I've gotten the modem to work, but I can't get the tcp connection example to work.  I've tried replacing the apn name "cmnet" with both "wap.cingular" and "isp.cingular," but I haven't had any luck. Can you recommend any next steps?

**Comment by goodwordalchemy** [comment]
Just upgraded my sim card to include voice and data, just to rule that out.  Still no luck

**Comment by goodwordalchemy** [comment]
GPRS_sendSMS example code works fine though, but still no luck with the TCP/IP connection.  Serial readout is:

"gprs join network error
gprs join network error
gprs join network error"

**Comment by goodwordalchemy** [comment]
new Development:

I re-downloaded all of my arduino libraries.  I had not installed them properly.  I am still not getting any connection with the default TCP connection in the example.  This is my serial readout now:

"IP Address is 10.0.181.0
connect error
waiting to fetch...
fetch over...
"

**Comment by mandyala** [comment]
any luck with the tcp/ip getting the same error
